const copy = {
  en: {
    workspaceMode: 'Workspace mode',
    repairMode: 'Repair track',
    createMode: 'Create route',
    eyebrow: 'FixYourTrack / Route Planner',
    title: 'Create a route from scratch.',
    lead: 'Place the start and finish. Shape the route. Export a clean GPX route.',
    instructionsButton: 'Instructions',
    projects: 'Projects',
    instructionsTitle: 'How to create a route',
    instructionsIntro: 'Build a planned route without inventing recorded activity data.',
    instructions: [
      {
        title: 'Place the route',
        steps: ['Click the map to place the start.', 'Click again to place the finish.', 'Drag any marker or edit its coordinates to refine the route.'],
      },
      {
        title: 'Shape and extend it',
        steps: ['Click the blue route to insert a waypoint.', 'Use Add waypoint for map placement, or Extend route to add a new finish.', 'Reverse the route or add a routed return to the start at any time.'],
      },
      {
        title: 'Draw off-grid sections',
        steps: ['Choose Draw off-grid, then click the map for each direct section.', 'Finish direct tracing to return to road routing.', 'You can switch each leg between routed and direct in the point list.'],
      },
      {
        title: 'Export safely',
        steps: ['Wait until every section is resolved.', 'Direct sections are allowed and shown as a warning.', 'Export creates a GPX route without timestamps or sensor data.'],
      },
    ],
    newRoute: 'New route',
    routeSummary: 'Route summary',
    routeName: 'Route name',
    draftLoading: 'Restoring local route draft\u2026',
    draftLoadFailed: 'Local route recovery is blocked. Your saved data has not been changed.',
    draftWriterBlocked: 'Create Route is already open in another app window. Close it there, then retry.',
    resetDraftLock: 'Reset damaged recovery lock',
    resetDraftLockConfirm: 'Close every other FixYourTrack window first. Reset the damaged local recovery lock?',
    retryDraftLoad: 'Retry recovery',
    preserveAndStartFresh: 'Preserve draft and start fresh',
    preserveDraftConfirm: 'Preserve this unreadable draft for recovery and start a new route?',
    draftPreserveFailed: 'The saved draft could not be preserved. Nothing was deleted.',
    draftChangedElsewhere: 'This route draft changed in another app window.',
    reloadSavedDraft: 'Reload saved draft',
    keepLocalDraft: 'Keep this route',
    keepLocalDraftConfirm: 'Preserve the other window\'s draft for recovery and keep this route instead?',
    activity: 'Activity',
    cycling: 'Cycling',
    walking: 'Walking',
    distance: 'Distance',
    routePoints: 'Route points',
    directSections: 'Direct sections',
    routingStatus: 'Routing status',
    draftSaved: 'Route draft saved locally',
    draftDirty: 'Local changes not saved yet',
    draftSaving: 'Saving local route draft\u2026',
    draftRestored: 'Local route draft restored',
    draftSaveFailed: 'Local route saving is unavailable. Export before closing the app.',
    localDraft: 'Local draft',
    saveToProjects: 'Save to projects',
    projectLoading: 'Checking saved project\u2026',
    projectDirty: 'Project has unsaved changes',
    projectSaving: 'Saving project\u2026',
    projectSaved: 'Project saved',
    projectSaveFailed: 'Project saving failed. Your route remains open.',
    projectConflictStatus: 'Project conflict',
    projectConflict: 'This project changed in another app window. Your edits are still open.',
    retryProjectSave: 'Retry save',
    reloadSavedProject: 'Reload saved version',
    saveAsCopy: 'Save as copy',
    projectsUnavailable: 'Local projects are unavailable.',
    replaceLocalConfirm: 'Continue without saving this local draft to Projects?',
    copyOfProject: 'Copy of {name}',
    projectCreated: 'Project created.',
    projectOpened: 'Project opened.',
    projectRenamed: 'Project renamed.',
    projectDuplicated: 'Project duplicated.',
    projectArchived: 'Project archived.',
    projectRestored: 'Project restored.',
    projectDeleted: 'Project permanently deleted.',
    empty: 'Waiting for start and finish',
    loading: 'Building route…',
    ready: 'Ready to export',
    error: 'Routing failed',
    buildRoute: 'Build route',
    placeStart: 'Place start',
    placeFinish: 'Place finish',
    addWaypoint: 'Add waypoint',
    extendRoute: 'Extend route',
    drawOffGrid: 'Draw off-grid',
    finishOffGrid: 'Finish off-grid tracing',
    reverseRoute: 'Reverse route',
    returnToStart: 'Return to start',
    undo: 'Undo',
    redo: 'Redo',
    clearRoute: 'Clear route',
    clearConfirm: 'Clear this route? The start, finish, waypoints, and unsaved edits will be deleted.',
    start: 'Start',
    finish: 'Finish',
    newFinish: 'New finish',
    waypoint: 'Waypoint',
    latitude: 'Latitude',
    longitude: 'Longitude',
    updateCoordinates: 'Update coordinates',
    addByCoordinates: 'Add {role} by coordinates',
    addCoordinatePoint: 'Add coordinate point',
    moveOnMap: 'Move on map',
    remove: 'Remove',
    outgoingLeg: 'Following section',
    routed: 'Follow mapped roads',
    direct: 'Direct / off-grid',
    exportTitle: 'Export',
    exportRoute: 'Export planned route',
    exportHelp: 'Exports GPX route points. No time, speed, heart-rate, power, cadence, or temperature data is invented.',
    directWarning: '{count} direct section(s) will be exported as drawn.',
    clickStart: 'Click the map to place the start. Press Escape to cancel.',
    clickFinish: 'Click the map to place the finish. Press Escape to cancel.',
    clickWaypoint: 'Click the map to add a waypoint. Press Escape to cancel.',
    clickExtend: 'Click the map to place a new finish. Press Escape to cancel.',
    clickDirect: 'Click the map for each direct section. Finish tracing or press Escape when done.',
    clickMove: 'Click the map to move the selected point. Press Escape to cancel.',
    routePlaced: 'Start and finish placed. The route is being built.',
    pointAdded: 'Route point added.',
    pointMoved: 'Route point moved.',
    routeReversed: 'Route direction reversed.',
    loopAdded: 'A routed return to the start was added.',
    exported: 'Planned GPX route exported.',
    useDirectForFailed: 'Use direct line for failed section',
    retryRouting: 'Retry routing',
    failedSection: 'Could not route from point {from} to point {to}. Your route points are safe.',
    mapRegion: 'Route planning map',
    mapLayer: 'Map layer',
    schemeLayer: 'Map',
    satelliteLayer: 'Satellite',
    closeWaypointCard: 'Close point editor',
    waypointDistance: 'Distance from start',
    waypointElevation: 'Elevation',
    notAvailable: 'Not available',
    incomingDirect: 'Set previous section as off-grid',
    outgoingDirect: 'Set following section as off-grid',
  },
  ru: {
    workspaceMode: 'Режим работы',
    repairMode: 'Исправить трек',
    createMode: 'Создать маршрут',
    eyebrow: 'FixYourTrack / Планировщик маршрутов',
    title: 'Создайте маршрут с нуля.',
    lead: 'Укажите старт и финиш. Настройте путь. Экспортируйте чистый GPX-маршрут.',
    instructionsButton: 'Инструкция',
    projects: 'Проекты',
    instructionsTitle: 'Как создать маршрут',
    instructionsIntro: 'Постройте плановый маршрут без выдуманных данных записанной активности.',
    instructions: [
      {
        title: 'Разместите маршрут',
        steps: ['Нажмите на карту, чтобы поставить старт.', 'Нажмите ещё раз, чтобы поставить финиш.', 'Перетаскивайте маркеры или изменяйте координаты для уточнения маршрута.'],
      },
      {
        title: 'Настройте и продлите путь',
        steps: ['Нажмите на синюю линию, чтобы вставить точку.', 'Используйте «Добавить точку» или «Продлить маршрут» для нового финиша.', 'Маршрут можно развернуть или замкнуть возвратом к старту.'],
      },
      {
        title: 'Нарисуйте участок вне дорог',
        steps: ['Выберите «Рисовать вне дорог» и ставьте точки прямого участка.', 'Завершите ручную трассировку, чтобы снова следовать дорогам.', 'Режим каждого участка можно изменить в списке точек.'],
      },
      {
        title: 'Безопасный экспорт',
        steps: ['Дождитесь построения всех участков.', 'Прямые участки разрешены и отмечены предупреждением.', 'Экспорт создаёт GPX-маршрут без времени и данных датчиков.'],
      },
    ],
    newRoute: 'Новый маршрут',
    routeSummary: 'Сводка маршрута',
    routeName: 'Название маршрута',
    draftLoading: 'Восстанавливаем локальный черновик маршрута\u2026',
    draftLoadFailed: 'Восстановление локального маршрута заблокировано. Сохранённые данные не изменены.',
    draftWriterBlocked: 'Режим создания маршрута уже открыт в другом окне приложения. Закройте его там и повторите попытку.',
    resetDraftLock: 'Сбросить повреждённую блокировку',
    resetDraftLockConfirm: 'Сначала закройте все остальные окна FixYourTrack. Сбросить повреждённую локальную блокировку восстановления?',
    retryDraftLoad: 'Повторить восстановление',
    preserveAndStartFresh: 'Сохранить копию черновика и начать заново',
    preserveDraftConfirm: 'Сохранить нечитаемый черновик для восстановления и начать новый маршрут?',
    draftPreserveFailed: 'Не удалось сохранить копию черновика. Ничего не удалено.',
    draftChangedElsewhere: 'Черновик маршрута изменился в другом окне приложения.',
    reloadSavedDraft: 'Загрузить сохранённый черновик',
    keepLocalDraft: 'Оставить этот маршрут',
    keepLocalDraftConfirm: 'Сохранить черновик из другого окна для восстановления и оставить этот маршрут?',
    activity: 'Активность',
    cycling: 'Велосипед',
    walking: 'Ходьба',
    distance: 'Расстояние',
    routePoints: 'Точки маршрута',
    directSections: 'Прямые участки',
    routingStatus: 'Статус построения',
    draftSaved: 'Черновик маршрута сохранён локально',
    draftDirty: 'Локальные изменения ещё не сохранены',
    draftSaving: 'Сохраняем локальный черновик маршрута\u2026',
    draftRestored: 'Локальный черновик маршрута восстановлен',
    draftSaveFailed: 'Локальное сохранение недоступно. Экспортируйте маршрут перед закрытием приложения.',
    localDraft: 'Локальный черновик',
    saveToProjects: 'Сохранить в проекты',
    projectLoading: 'Проверяем сохранённый проект\u2026',
    projectDirty: 'В проекте есть несохранённые изменения',
    projectSaving: 'Сохраняем проект\u2026',
    projectSaved: 'Проект сохранён',
    projectSaveFailed: 'Не удалось сохранить проект. Маршрут остался открытым.',
    projectConflictStatus: 'Конфликт проекта',
    projectConflict: 'Проект был изменён в другом окне приложения. Ваши правки остаются открытыми.',
    retryProjectSave: 'Повторить сохранение',
    reloadSavedProject: 'Загрузить сохранённую версию',
    saveAsCopy: 'Сохранить как копию',
    projectsUnavailable: 'Локальные проекты недоступны.',
    replaceLocalConfirm: 'Продолжить, не сохраняя этот локальный черновик в проекты?',
    copyOfProject: 'Копия — {name}',
    projectCreated: 'Проект создан.',
    projectOpened: 'Проект открыт.',
    projectRenamed: 'Проект переименован.',
    projectDuplicated: 'Копия проекта создана.',
    projectArchived: 'Проект перемещён в архив.',
    projectRestored: 'Проект восстановлен.',
    projectDeleted: 'Проект удалён безвозвратно.',
    empty: 'Ожидаются старт и финиш',
    loading: 'Строим маршрут…',
    ready: 'Готов к экспорту',
    error: 'Ошибка построения',
    buildRoute: 'Построение маршрута',
    placeStart: 'Поставить старт',
    placeFinish: 'Поставить финиш',
    addWaypoint: 'Добавить точку',
    extendRoute: 'Продлить маршрут',
    drawOffGrid: 'Рисовать вне дорог',
    finishOffGrid: 'Завершить ручную трассировку',
    reverseRoute: 'Развернуть маршрут',
    returnToStart: 'Вернуться к старту',
    undo: 'Отменить',
    redo: 'Повторить',
    clearRoute: 'Очистить маршрут',
    clearConfirm: 'Очистить маршрут? Старт, финиш, все точки и несохранённые изменения будут удалены.',
    start: 'Старт',
    finish: 'Финиш',
    newFinish: 'Новый финиш',
    waypoint: 'Точка',
    latitude: 'Широта',
    longitude: 'Долгота',
    updateCoordinates: 'Обновить координаты',
    addByCoordinates: 'Добавить точку «{role}» по координатам',
    addCoordinatePoint: 'Добавить точку',
    moveOnMap: 'Переместить на карте',
    remove: 'Удалить',
    outgoingLeg: 'Следующий участок',
    routed: 'Следовать дорогам',
    direct: 'Прямой / вне дорог',
    exportTitle: 'Экспорт',
    exportRoute: 'Экспортировать плановый маршрут',
    exportHelp: 'Экспортирует точки GPX-маршрута. Время, скорость, пульс, мощность, каденс и температура не создаются.',
    directWarning: 'Прямых участков: {count}. Они будут экспортированы как нарисованы.',
    clickStart: 'Нажмите на карту, чтобы поставить старт. Escape отменяет действие.',
    clickFinish: 'Нажмите на карту, чтобы поставить финиш. Escape отменяет действие.',
    clickWaypoint: 'Нажмите на карту, чтобы добавить точку. Escape отменяет действие.',
    clickExtend: 'Нажмите на карту, чтобы поставить новый финиш. Escape отменяет действие.',
    clickDirect: 'Ставьте точки прямого участка на карте. Завершите трассировку или нажмите Escape.',
    clickMove: 'Нажмите на карту, чтобы переместить выбранную точку. Escape отменяет действие.',
    routePlaced: 'Старт и финиш размещены. Маршрут строится.',
    pointAdded: 'Точка маршрута добавлена.',
    pointMoved: 'Точка маршрута перемещена.',
    routeReversed: 'Направление маршрута изменено.',
    loopAdded: 'Добавлен возврат к старту по дорогам.',
    exported: 'Плановый GPX-маршрут экспортирован.',
    useDirectForFailed: 'Прямая линия для проблемного участка',
    retryRouting: 'Повторить построение',
    failedSection: 'Не удалось построить участок от точки {from} до точки {to}. Точки маршрута сохранены.',
    mapRegion: 'Карта планирования маршрута',
    mapLayer: 'Слой карты',
    schemeLayer: 'Карта',
    satelliteLayer: 'Спутник',
    closeWaypointCard: 'Закрыть редактор точки',
    waypointDistance: 'Расстояние от старта',
    waypointElevation: 'Высота',
    notAvailable: 'Нет данных',
    incomingDirect: 'Предыдущий участок вне дорог',
    outgoingDirect: 'Следующий участок вне дорог',
  },
}

export function getCreateRouteCopy(language) {
  return copy[language] ?? copy.en
}

export function formatCreateRouteCopy(template, values = {}) {
  return Object.entries(values).reduce(
    (result, [name, value]) => result.replaceAll(`{${name}}`, String(value)),
    template,
  )
}
